name: Check documentation

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: Generate documentation for core and provider
        run: |
          yarn install --ignore-engines
          yarn nx run-many --target=docs
      - name: Doc linter
        run: |
          yarn install
          yarn lint:docs