# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pull-request-catalog-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "17.x"
          registry-url: https://registry.npmjs.org/
      - run: cd lib && yarn install --ignore-engines
      - run: cd lib && yarn ts:lint
      - run: cd lib && yarn test
      - run: cd lib && yarn build:tsc
  pull-request-catalog-providers: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "17.x"
          registry-url: https://registry.npmjs.org/
      - run: cd providers && yarn install --ignore-engines
      - run: cd providers && yarn ts:lint
      - run: cd providers && yarn test
      - run: cd providers && yarn build:tsc


