name: Tests Nightly

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          yarn
      - name: Compile
        run: |
          yarn run build
      - name: Setup NVM
        run: |
          docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
          sudo chmod go+r /etc/hosts
          sudo echo "127.0.0.1  nevermined-metadata" | sudo tee -a /etc/hosts
          git clone https://github.com/nevermined-io/tools

          cd tools
          export KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"
          rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"

          export KEEPER_VERSION=v3.0.0
          ./start_nevermined.sh --no-node --opengsn 2>&1 | tee nevermined_tools.txt &
          cd ../lib
          ./scripts/wait-nevermined.sh
      - name: Integration subgraph tests
        env:
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
        run: cd lib && yarn artifacts:download && yarn test:subgraph

      