# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Testing

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]

jobs:
  unit-test-with-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: yarn install --ignore-engines
      - name: Linter
        run: yarn nx run-many --target=lint
      - name: Unit tests
        run: yarn nx run-many --target=test:unit
      - name: Build
        run: yarn nx run-many --target=build
  integration-tests-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17.x"
          registry-url: https://registry.npmjs.org/
      - uses: nevermined-io/nvm-tools-actions@v0.11.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          opengsn: 'true'
          estuary: 'true'
          contracts-version: 'v3.2.1'
      - name: Install packages
        run: yarn install --ignore-engines
      - name: Check artifacts
        run: |
          nvm-tools copy-artifacts ./catalog/artifacts
          nvm-tools copy-circuits ./catalog/circuits
          ls -l ./catalog/artifacts
      - name: Integration tests
        env:
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
        run: yarn nx test:integrations catalog
