# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['lib', 'providers']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "17.x"
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: cd ${{ matrix.module }} && yarn install --ignore-engines
      - name: Linter
        run: cd ${{ matrix.module }} && yarn ts:lint
      - name: Unit tests
        run: cd ${{ matrix.module }} && yarn test:unit
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Integration tests
        env:
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}
        run: cd lib && yarn artifacts:download && yarn test:integrations
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ['lib', 'providers']
    steps:
      - name: Build
        run: cd ${{ matrix.module }} && yarn build:tsc
