# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pull-request-catalog-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "17.x"
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: cd lib && yarn install --ignore-engines
      - name: Linter
        run: cd lib && yarn ts:lint
      - name: Unit tests
        run: cd lib && yarn test:unit
      - name: Integration tests
        env:
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN}}
        run: cd lib && ./scripts/download-artifacts.sh && yarn test:integrations
      - name: Build
        run: cd lib && yarn build:tsc
  pull-request-catalog-providers: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "17.x"
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: cd providers && yarn install --ignore-engines
      - name: Linter
        run: cd providers && yarn ts:lint
      - name: Unit tests
        run: cd providers && yarn test
      - name: Build
        run: cd providers && yarn build:tsc


