name: Run Unit Tests

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!*release*'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    # env:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        npm install -g npm
        npm i
    - name: Run Unit Tests
      run: npm run test
